### ISSUE TITLE
HTTP server binds on 0.0.0.0 with anonymous admin by default.

### ISSUE THREAD

**Issue by john9x** [glowroot/glowroot#100]
Hi!

HTTP server binds on 0.0.0.0 with anonymous admin by default. I think it's a bad idea due to security reasons. Especially considering that Glowroot always writes to the log "Glowroot listening at http://localhost:" and configuration options not described.
To find option `ui.bind.address` need to dive into code. :)

**Comment by trask** [comment]
I'm glad you found `ui.bind.address`. You're right that needs to be much much easier. I pushed commit to change that to a normal configuration property:

![capture](https://cloud.githubusercontent.com/assets/218610/16463090/1b5173de-3de9-11e6-8df7-e084271c9ab2.PNG)

Also, I see your point about that startup message being misleading, so I changed it to `Glowroot UI listening on port 4000` (avoiding use of word `localhost`).

I'm not sure whether to change the defaults since I want it to avoid confusion for first time users.

**Comment by john9x** [comment]
> Also, I see your point about that startup message being misleading, so I changed it to Glowroot UI listening on port 4000 (avoiding use of word localhost).
But why not to write the real bind address?

>I'm not sure whether to change the defaults since I want it to avoid confusion for first time users.
IMHO If this will be described in the README (and other configuration options)  users will not confusing.

PS. I love Glowroot! Right after installation I have found miscached query and a few possible bottlenecks. Thanks for you work!

**Comment by trask** [comment]
Thanks, I made the change to the startup message and the default bind address.

To try to avoid confusion of first time users, I added an additional startup message about changing the bind address if needed, and also added notes to the [Installation](https://github.com/glowroot/glowroot/wiki/Installation) page.

**Comment by amitsinghpratap** [comment]
There should be configuration option for address binding even at the time of installation. As it is not always possible to access it on localhost even for the first time.

**Comment by trask** [comment]
Hi, does https://github.com/glowroot/glowroot/wiki/Agent-Installation#optional-post-installation-steps help?  Or do you have something else in mind.  Thanks.

**Comment by trask** [comment]
It's not clear from the wiki, but you can pre-populate the `admin.json` file, e.g.

```
{
  "web": {
    "port": 4000,
    "bindAddress": "0.0.0.0"
  }
}
```

**Comment by kengibous** [comment]
I believe i have ran into an issue using glowroot inside docker containers.  Since the admin.json is created binding to 127.0.0.1 on port 4000 - I am unable to bind host operating system to the glowroot port - I believe if 0.0.0.0 is default binding then it would work.  Has anyone used glowroot inside a docker container?

**Comment by trask** [comment]
Hi @kengibous, you can manually create the `admin.json` file when installing glowroot in order to change the port binding, e.g.

```
{
  "web": {
    "port": 4000,
    "bindAddress": "0.0.0.0"
  }
}
```

**Comment by tholu** [comment]
@kengibous Have you successfully managed to dockerize glowroot?
