### ISSUE TITLE
Problem with change Glowroot storage from H2 to MySQL

### ISSUE THREAD

**Issue by bogdan580** [glowroot/glowroot#1001]
Hi
I run Spring application in Tomcat server with added Glowroot. By default Glowroot use H2 db and everything looks fine.
But when I try run app in Docker container I have problem with logs history. When application crash then I lost all logs. I have external MySQL DB and I tried to add glowroot.properties file to change H2 database, but it Glowroot still save logs in H2.
Do you have some tutorial for my case?
Or need install Cassandara with Glowroot central? 

Apache Tomcat 9.0.62
Glowroot version: 0.13.6, built 2020-03-01
jdk1.8.0_161

**Comment by Nowheresly** [comment]
HI @bogdan580 

when using h2 and if you want to keep you data when your application is running using docker, you should declare a docker volume and configure glowroot to put its data files in this volume. This way, you will not loose your data after each restart.
To specifiy the data directory for h2, you can refer to the documentation here:
https://github.com/glowroot/glowroot/wiki/Agent-Installation-%28with-Embedded-Collector%29#changing-up-the-directory-locations

Of course, if you use the central collector with cassandra (the recommended approach) you won't loose your data as well since they are persisted in cassandra.

You can see how to use collector here:
https://github.com/glowroot/glowroot/wiki/Agent-Installation-%28for-Central-Collector%29

**Comment by bogdan580** [comment]
Thank @Nowheresly for the answer.
I'll try to configure second case it will be better for prod environment.
Is it possible to save logs in MySQL without using Cassandra and Central collector?

**Comment by Nowheresly** [comment]
No, only cassandra is supported.

**Comment by bogdan580** [comment]
Ok, thanks
