### ISSUE TITLE
jvm/thread-dump did not display the thead's id, example: to find which thread cause cpu high-load

### ISSUE THREAD

**Issue by javalover123** [glowroot/glowroot#102]

**Comment by trask** [comment]
Thanks for submitting this.  I have added thread id to the thread dump, using similar format as displayed by jstack, you can see at https://demo.glowroot.org/jvm/thread-dump

This is now in the latest snapshot build https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9.1-SNAPSHOT-dist.zip

**Comment by javalover123** [comment]
Thanks, resolved fast. It will be more better, if this thread id is equals jstack's nid.

**Comment by trask** [comment]
Sure, that makes sense, re-opening to investigate how to obtain native thread id.

**Comment by trask** [comment]
Native thread id does not seem very easy to obtain, so I added a raw jstack view instead which contains the info.  On the thread dump view, there is now a link to "View jstack thread dump" (as long as jstack is available, e.g. you must be using the JDK and not the JRE).  You can see this on the demo site at https://demo.glowroot.org/jvm/thread-dump.

**Comment by javalover123** [comment]
Great job! Can you add extra nid as decimal system?

**Comment by trask** [comment]
Can you explain your diagnostic workflow?  I'm guessing you are seeing high cpu utilization, then using something like `top -H` to identify native thread id, then looking to see what corresponding java thread is doing?

In the normal Glowroot thread dump view, are you seeing too many threads under `Matched threads (matched to currently executing transactions)`, making it difficult to identify the root cause of high cpu utilization from that view alone?  What if the thread dump view displayed cpu/waited/blocked time for these matched threads (same value as when you open the trace for an individual matched thread and look at cpu/waited/blocked time), would this eliminate your need to look at `top -H` and map native thread id to java thread?

**Comment by javalover123** [comment]
Get thread id by top -H is decimal system, and nid by jstack is hex, they are not equal.

**Comment by trask** [comment]
Right.  So is my assumption above correct on your workflow, and would displaying cpu time of current transaction in the thread dump eliminate your need to look at `top -H` in the first place?

**Comment by javalover123** [comment]
That's right, if you do this.

**Comment by trask** [comment]
CPU time is now displayed in the thread dump view, e.g.
![threaddump](https://cloud.githubusercontent.com/assets/218610/17949164/f6c04e90-6a08-11e6-8e96-c06f362d1fb3.PNG)

Also, I removed the jstack link on the thread dump view, since it could be confusing for why have jstack in addition to normal thread view, and hopefully jstack is not needed anymore, but you can still access the jstack view using direct url (e.g. https://demo.glowroot.org/jvm/jstack) if needed.

**Comment by javalover123** [comment]
Great work! Thanks.

**Comment by jibsonline** [comment]
Has this been merged to release? I can't find the CPU time in thread dump report

**Comment by trask** [comment]
Hi @jibsonline, what does Glowroot report under JVM > Environment > Java (both Version and VM)?

Also, can you go to /jvm/capabilities (e.g. manually go to that url instead of /jvm/environment) and see what Glowroot reports for "Thread CPU time"?

Thanks,
Trask

**Comment by jibsonline** [comment]
@trask 

Capabilities
Thread CPU time ON
Thread contention time ON
Thread allocated bytes ON

**Comment by trask** [comment]
That looks good.

Are you seeing something like the screenshot above, but just without CPU time line? Can you post a screenshot?

Thanks,
Trask

**Comment by jibsonline** [comment]
![image](https://user-images.githubusercontent.com/1730931/42019645-43ff8bb2-7ad3-11e8-8725-2effd4fae757.png)

**Comment by jibsonline** [comment]
@trask I am only getting "Unmatched threads". There are no matched threads in my thread. I am using Spring Boot 1.5.10. Is there not support for it?
