### ISSUE TITLE
Can transaction/queries sort by " Time per execution" default? Not Total time (ms)

### ISSUE THREAD

**Issue by javalover123** [glowroot/glowroot#103]

**Comment by trask** [comment]
Hi, thanks for submitting issue.  Sort desc by total time seems most common default among tools I've used, since it gives the most wholistic view first.  Sort desc by time per execution is also great of course.  The sort column/order is reflected in the current url, so you could bookmark it if you find yourself viewing with one particular sort frequently.  Please let me know if you have other thoughts.

**Comment by javalover123** [comment]
Sort desc by total time is good, and Sort desc by time per execution can see which sql cost much more time per execution.
Can you add a configuration to set Sort desc by total time or Sort desc by time per execution?

**Comment by trask** [comment]
Sorry for the late reply, I'm not sure a configuration to change the default sort here is very useful.  It seems better generally to look at total first (execution count * time per execution), since improving a query that runs 1000 times at 100 milliseconds each (either by reducing execution count or by reducing time per execution) is generally going improve system performance much more than improving a query that runs 1 time for 500 milliseconds.
