### ISSUE TITLE
Error with jgroups-tcp.xml file with cluster configuration [version 0.14.1]

### ISSUE THREAD

**Issue by pattinik** [glowroot/glowroot#1070]
Hi, I have an install of glowroot version 0.14.0 in cluster configuration with java11 and cassandra version 4.0 (with two cluster nodes).
glowroot-central.proprierties file is configured as below. This configuration works fine, but when I tried to update it to 0.14.1 version, I got this error:

> 
> "Error while trying to create a channel using the specified configuration file: jgroups-tcp.xml
> org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000085: Error while trying to create a channel using the specified configuration file: jgroups-tcp.xml"

What is wrong with new version?

```
#############################################
## Cluster configuration
jgroups.configurationFile=jgroups-tcp.xml
jgroups.symEncryptAlgorithm=AES/CBC/PKCS5Padding
jgroups.symEncryptKeystoreName=/path/to/glowroot-central-0.14.1/jgroups.keystore
jgroups.symEncryptKeystorePassword=xxxxxx
jgroups.symEncryptKeyAlias=yyyyy
jgroups.symEncryptKeyPassword=zzzzzzzz
jgroups.localAddress=glowroot-central1.local
jgroups.localPort=7800
jgroups.initialNodes=glowroot-central1.local:7800,glowroot-central2.local:7800
collector.address=http://glowroot-central1.local:8181,http://glowroot-central2.local:8181
```

**Comment by Nowheresly** [comment]
Hi @pattinik 
Thanks for your report.

I see the real error is this one:
` Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=78, too big.`

Jgroups changed the default keystore from jks to pkcs12 !
See here: https://github.com/belaban/JGroups/commit/c6f50e5f73609e71d23090274dfd85b7045a69ac

So it tries to read the jks provided as a pkcs12 file...

So either you change the jgroups-tcp.xml file and you add
`keystore_type="JCEKS"`
as attribute to the SYM_ENCRYPT tag

Or you convert your jks to the pkcs12 format, for example using a command like:

`keytool -importkeystore -srckeystore jgroups.keystore -srcstoretype JCEKS -deststoretype PKCS12 -destkeystore keystore.p12
`

**Comment by Nowheresly** [comment]
The wiki page has been updated accordingly:

https://github.com/glowroot/glowroot/wiki/Central-Collector-Cluster

**Comment by pattinik** [comment]
Thank you very much! @Nowheresly
