### ISSUE TITLE
Compute APM index

### ISSUE THREAD

**Issue by cecrdle** [glowroot/glowroot#162]
Hi,
thank you for excelent project. We are running on successfully on Tomcat and RedHat Jboss Fuse.
It wourld be fine compute and showing APM index as graph and the as number for transactions.

APM index is a number 0–100:
* If the server response time for all transactions is less than SLA, then APM index
= 100.
* If the response time for all transactions was longer than four times the specified
SLA, then APM index = 0.
It is therefore a simple universal metric for expressing the overall performance of the
application with a number between 0 and 100.
The specific formula to calculate the APM index is:
 APMI=(L1+25 %*L2+50%*L3+75%*L4)/CNT*100

* L1 = count of transactions with server response time lower than SLA
* L2 = count of transactions with server response time between SLA and 2nd
multiple of SLA
* L3 = count of transactions with server response time between 2nd and 3rd
multiple of SLA
* L4 = count of transactions with server response time between 3rd and 4th multiple
of SLA
* CNT = total transaction count

**Comment by trask** [comment]
Hi, thanks for posting!  This sounds like a variant on [Apdex](https://en.wikipedia.org/wiki/Apdex) score (btw, I think you mean 75%*L2 instead of 25%*L2 in the formula above).

I personally prefer percentiles since they are such a common terminology already, and so "the 95th percentile is 2 seconds" is much easier for most people to understand compared to "the apdex score is 90 based on a 1 second Apdex threshold".

I have the impression (maybe wrong) that Apdex was created to avoid the difficulty/cost of aggregating percentiles.  Glowroot already uses the excellent https://github.com/HdrHistogram/HdrHistogram to capture and aggregate response time histograms which allows for displaying arbitrary percentiles over arbitrary time periods.  This is slightly more costly compared to capturing and aggregating Apdex scores, but the HdrHistogram library does a great job of minimizing this additional cost.

Can you give some background on why this Apdex measure is useful for you?

Thanks,
Trask

**Comment by cecrdle** [comment]
Hi,
you are right this is similar to apdex score (I originaly thing that it is the same]. The apdex is used for example in report of Jmeter 3.x, Apm index use for example this product https://www.flowmon.com/en/products/flowmon/application-performance-monitor.

I saw the graph percentile but I overlook computed numbers under graph, it looks useful for me. 

Now it's possible to sort transaction by percent of time time/by average time/by throwput. What is missing me is possibility sort the transactions by quality to response times. Maybe include percentile or apdex to combo.

**Comment by trask** [comment]
Adding another transaction sort option is a nice idea.  And this could be a good use of apdex score, as sorting on percentiles would be pretty expensive (would require loading histograms for all named transactions), compared to sorting on apdex which is just slightly more expensive than sorting on average.

**Comment by cecrdle** [comment]
Hi,
I agree, sorting by apdex score meets my expectations.

**Comment by trask** [comment]
Closing for now, tagged with `wishlist` label (lower priority enhancements that have been closed to keep the open backlog manageable).
