### ISSUE TITLE
Collector server behind load balancer

### ISSUE THREAD

**Issue by adnaan** [glowroot/glowroot#180]
Hi, 
       What is the recommended approach to have a round-robin load balancer setup?

I want to run three instances of collector server behind Haproxy in expectation of higher load due to the numerous services in our company looking to integrate. Is that possible? Does the glowroot server store metrics in-memory before writing to Cassandra? 

-Thanks

P.S: Work is progressing slowly but surely on Go and Node agents. Looking forward to opening up the code on github in a couple of weeks.

**Comment by trask** [comment]
Hi, there are a couple things needed for glowroot central to support clustering:

* Invalidating caches needs to be cluster wide (e.g. [ConfigDao.java#L153](https://github.com/glowroot/glowroot/blob/v0.9.12/central/src/main/java/org/glowroot/central/repo/ConfigDao.java#L153))
* Central UI features that query the connected agents directly (e.g. to display thread dump) need to first find the cluster member that the agent is connected to, and then query the agent through that cluster member
* Possible duplicate alert notifications need to be prevented

Duplicate rollups are possible, but don't need to be prevented since the rollups are idempotent, and should be rare enough that they should not cause significant unnecessary work.

I'm thinking to use [hazelcast](https://hazelcast.org/) in addressing the above issues.  I'll target for v0.9.13.

And thanks for update on Go/Node agents, great to hear they are coming along!

Trask

**Comment by adnaan** [comment]
Great to hear! Thanks!

**Comment by trask** [comment]
Hi @adnaan,

See the new Wiki section on how to configure a central collector cluster: https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation#running-a-central-collector-cluster

I haven't documented this part yet, but on the agent side, `glowroot.properties` now uses `collector.address` instead of `collector.host` and `collector.port`, so that it can be a comma-separated list of collectors, e.g.

```
collector.address=central1:8181,central2:8181
```

which will do load balancing on the client side.

Or you can point `collector.address` at an HTTP/2 load balancer to do load balancing at the server side (I haven't tried this out yet).

Let me know if you get this working, or if you run into any issues.

Thanks,
Trask

**Comment by adnaan** [comment]
Hi,
 Thanks for the speedy work. I am going to try and test this configuration by this weekend. 
-Best
Adnaan

**Comment by adnaan** [comment]
Hi,
Setting up the load balancer is taking more time then expected. Will update.

**Comment by anishkh** [comment]
Hi Trask,
I have tested the clustering version. It works great from the client side. When one of the central server is not available the client agent connects to the next available one.  One issue ,I  noticed is that the central server UI is only able to pull up live data (threaddump) from the agents  which are connected to that central server node.   If the original central server goes down then the agent connect to available one   and everything works fine. It has the functionality (live data pull) to work from any central node in the cluster. Right?  My Multicast UDP set up is working fine based on the sender and receiver test.  

Thanks,
Anish

**Comment by trask** [comment]
Can you post the glowroot central log files from both nodes?  I'd like to see the jgroups logging in particular.  Thanks.

**Comment by anishkh** [comment]
logs attached.

[glowroot-server2.zip](https://github.com/glowroot/glowroot/files/975227/glowroot-server2.zip)

**Comment by trask** [comment]
I can see from log file that the nodes aren't finding each other.  Jgroups is picking up your local IPv6 address, which could be the issue.  Can you try running both nodes with `-Djava.net.preferIPv4Stack=true`?

**Comment by anishkh** [comment]
That didn't help. It could be network/firewall issue. I will test with some of the jgroup demo programs and see if I can narrow down the issue.

**Comment by trask** [comment]
Have a look also at https://github.com/glowroot/glowroot/issues/201#issuecomment-297629111

**Comment by anishkh** [comment]
Thank you very much Trask. I tried the tcp option and it worked fine and I had to disable some firewall to make it work in UDP.  Both options work fine now.  -Djava.net.preferIPv4Stack=true option is required in both settings.

**Comment by anishkh** [comment]
Hi,
I'm getting an exception when adding 3rd server to central cluster.  It seems it only works with 2 servers. 

" Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
	at org.glowroot.central.DownstreamServiceImpl.$deserializeLambda$(DownstreamServiceImpl.java:101)" 

Please see the attached log for details.
[glowroot.zip](https://github.com/glowroot/glowroot/files/988317/glowroot.zip)

**Comment by trask** [comment]
Can you post log files from all nodes?  Thanks

**Comment by anishkh** [comment]
See logs from all 3 nodes. 

[glowroot-servers.zip](https://github.com/glowroot/glowroot/files/988755/glowroot-servers.zip)

**Comment by trask** [comment]
It looks like node 3 is running a different version from the other 2, that could be the issue.

**Comment by anishkh** [comment]
I will upgrade and check  but if I start node 3 first or second then it works fine and the issue will shift to the last one.

**Comment by trask** [comment]
Hi @anishkh, I happened to get "Invalid lambda deserialization" exception while testing locally.  In my case it was because one of my nodes had been compiled with javac, while the other node had been compiled with eclipse compiler (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=516620).  Not sure if this is the same cause as in your case, but I still think getting all nodes onto the exact same build is likely to resolve the issue.

**Comment by anishkh** [comment]
Thanks for checking on this Trask. I have downloaded the 0.9.16 binary version on all nodes but it still didn't work. I got a different exception this time than before.   It works any combination of servers as long as I have 2 nodes. Once I add the 3rd node the error starts happening. I  only tried with UDP.  I will test TCP later. It could be some network/firewall related issue but not sure.  Here is the trace I got. 

2017-05-11 22:32:40.688 ERROR org.glowroot - Unable to invoke method public void
 org.infinispan.statetransfer.StateTransferManagerImpl.waitForInitialStateTransf
erToComplete() throws java.lang.Exception on object of type StateTransferManager
Impl
org.infinispan.commons.CacheException: Unable to invoke method public void org.i
nfinispan.statetransfer.StateTransferManagerImpl.waitForInitialStateTransferToCo
mplete() throws java.lang.Exception on object of type StateTransferManagerImpl
        at org.infinispan.commons.util.SecurityActions.lambda$invokeAccessibly$0
(SecurityActions.java:95)
        at org.infinispan.commons.util.SecurityActions.doPrivileged(SecurityActi
ons.java:83)
        at org.infinispan.commons.util.SecurityActions.invokeAccessibly(Security
Actions.java:88)
        at org.infinispan.commons.util.ReflectionUtil.invokeAccessibly(Reflectio
nUtil.java:165)
        at org.infinispan.factories.AbstractComponentRegistry$PrioritizedMethod.
invoke(AbstractComponentRegistry.java:869)
        at org.infinispan.factories.AbstractComponentRegistry.invokeStartMethods
(AbstractComponentRegistry.java:635)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(Abst
ractComponentRegistry.java:624)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComp
onentRegistry.java:549)
        at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.ja
va:231)
        at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:803)
        at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDeleg
atingCache.java:411)
        at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultC
acheManager.java:652)
        at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheMa
nager.java:592)
        at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCa
cheManager.java:456)
        at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManag
er.java:446)
        at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManag
er.java:431)
        at org.glowroot.central.util.ClusterManager$ClusterManagerImpl.createCac
he(ClusterManager.java:107)
        at org.glowroot.central.repo.CentralConfigDao.<init>(CentralConfigDao.ja
va:75)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:174)
        at org.glowroot.central.CentralModule.<init>(CentralModule.java:112)
        at org.glowroot.central.Bootstrap.main(Bootstrap.java:30)
Caused by: org.infinispan.commons.CacheException: Initial state transfer timed o
ut for cache centralConfigCache on zltc5jbs-28968
        at org.infinispan.statetransfer.StateTransferManagerImpl.waitForInitialS
tateTransferToComplete(StateTransferManagerImpl.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.infinispan.commons.util.SecurityActions.lambda$invokeAccessibly$0
(SecurityActions.java:91)
        ... 20 common frames omitted
2017-05-11 22:32:42.946 INFO  o.i.r.t.jgroups.JGroupsTransport - ISPN000080: Dis
connecting JGroups channel ISPN
2017-05-11 22:32:43.010 INFO  o.i.r.t.jgroups.JGroupsTransport - ISPN000082: Sto
pping the RpcDispatcher for channel ISPN

**Comment by trask** [comment]
@anishkh yeah, try with TCP, that is easier to troubleshoot from networking perspective.  If you have issue with TCP, please post log files from all 3 nodes.  Thanks.

**Comment by anishkh** [comment]
Hi Trask, I tried with version 0.9.17 , both tcp and udp settings are working fine in a 3 node cluster set up.

**Comment by pacific28** [comment]
Hi Trask,
I'm using Nginx as Load Balancer for Server Side. Nginx Config is as such:
=======================================================
http {
	upstream grpcservers {
	    server server1:7878;  #ip of collector 
	}	
	server {
	        listen 8181 http2;
	        server_name  server1; #ip of collector 
	        location / {
        	    proxy_pass http://grpcservers;
        	}
    	}
===========================

Just to check it works fine with load balancer or not. Ideally what nginx should do, run on 8181 port of server & redirect traffic to 7878 port. But  glowroot collector is not getting connected to agent at all. And the agent log is:
---------------------------------------------------------
2018-09-10 12:32:32.538 WARN  o.g.agent.central.CentralConnection - unable to establish connection with the central collector http://server1:8181(will keep trying...): First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f.

**Comment by trask** [comment]
Hi @pacific28, check out https://www.nginx.com/blog/nginx-1-13-10-grpc/. Starting with Nginx 1.13.10 you can use:

```
location / {
    grpc_pass grpc://grpcservers;
}
```

**Comment by parabinda** [comment]
> Hi,
> What is the recommended approach to have a round-robin load balancer setup?
> 
> I want to run three instances of collector server behind Haproxy in expectation of higher load due to the numerous services in our company looking to integrate. Is that possible? Does the glowroot server store metrics in-memory before writing to Cassandra?
> 
> -Thanks
> 
> P.S: Work is progressing slowly but surely on Go and Node agents. Looking forward to opening up the code on github in a couple of weeks.

@adnaan 
You mentioned about - Go and Node agent work you were doing quite a while ago slated to complete soon.

Is it possible for you to share the - GO and Node agent, if it is available?

Thank you,
Arabinda
