### ISSUE TITLE
Elasticsearch requests parameters missing 

### ISSUE THREAD

**Issue by hgomez** [glowroot/glowroot#228]
I could see ES parameters next to ES request in transaction/traces/trace entries, ie 

    elasticsearch execution: SEARCH rules/activeRule { "bool" : { "must" : { "terms" : { "key" : [ ] } } } }

But they miss on Queries/ES 

    SEARCH rules/activeRule

It would be nice to have them here too

**Comment by trask** [comment]
Hi @hgomez, this is done.  My concern is that since Elasticsearch doesn't have "bind parameter" concept, the entire query including any user supplied value(s) will be used for aggregation, which could make the aggregation less useful (not enough aggregation).  I agree though that with the way it was before this change, the aggregation was probably even _more_ less useful (way too much aggregation).  Would appreciate your thoughts once you have a chance to try this out.  Thanks.

**Comment by hgomez** [comment]
I'll review and bring feedbacks. Thanks again to take care of ES users ;)
