### ISSUE TITLE
Unable to instrument java agent on windows

### ISSUE THREAD

**Issue by vijayninave** [glowroot/glowroot#267]
Hi Team,

We are unable to instrument glowroot agent on java based windows server. I updated the details as per standard process. Please find the attached logs file & start-up script for your reference. Kindly validate the same & let me know for further instrumentation.

Regards,
Vijay.
[glowroot.2017-08-28.zip](https://github.com/glowroot/glowroot/files/1256788/glowroot.2017-08-28.zip)

[Start-up script.txt](https://github.com/glowroot/glowroot/files/1256776/Start-up.script.txt)

**Comment by trask** [comment]
Hi @vijayninave, it looks like you have configured the `collector.address` in your agent's `glowroot.properties` file to point to the central collector's `ui.port` (4000) instead of pointing to the central collector's `grpc.port`.  Please see https://github.com/glowroot/glowroot/wiki/Central-Collector-Installation#agent-installation.

**Comment by trask** [comment]
Closing, but please re-open if you have additional questions about this.
