### ISSUE TITLE
Add possibility to dynamically attach glowroot agent after VM startup 

### ISSUE THREAD

**Issue by Tradunsky** [glowroot/glowroot#308]
We have restricted environment that we want to monitor. Sometimes we would need to turn on and turn off glowroot on demand. For this we are missing that possibility to attach glowroot agent from the application code:
Starting Agents After VM Startup
https://docs.oracle.com/javase/6/docs/api/java/lang/instrument/package-summary.html

**Comment by Tradunsky** [comment]
I believe it is not just about adding a line into MANIFEST. I was not sure if it is feasible in the case of glowroot, so I wanna ask @trask first: if the framework not aimed to change classes structure?

If not, I guess it could be done by using same facilities like in the example:
https://github.com/pingtimeout/tyrion/issues/1

**Comment by trask** [comment]
Hi @Tradunsky, thanks for posting! There are a few places where Glowroot changes class structure, e.g. adding a field in PreparedStatement implementations to track the original sql text, and adding a field in Runnable implementations to track transaction execution across multiple threads.

**Comment by trask** [comment]
Tagged with wishlist and closing for now to keep the open backlog manageable.  This would be nice, but would probably require applying some subset of instrumentation, and running with reduced functionality if loaded after VM startup.

**Comment by Tradunsky** [comment]
Makes sense.

Thanks for you quick replay!

**Comment by xuegao1** [comment]
Hello @trask, our project is trying to attach glowroot dynamically as well, but failed with the latest version 0.14.0, since Agent-Class not mentioned in the Manefest.mf file.

After some search, I find the discussion listed here. Since the discussion is from the year 2018, I am wondering whether this feature is already present in the latest glowroot version 0.14.0? If not, is it in the plan to add it? Thanks!
