### ISSUE TITLE
Ad hoc report is showing old agents

### ISSUE THREAD

**Issue by webjoel** [glowroot/glowroot#332]
In Glowroot Central version 0.10.4, menu "Reporting", option "Ad hoc report":

List of "Agents" show old agents, different of the list on others menus (e.g "Transactions"), where show correct agents.

**Comment by trask** [comment]
Hi @webjoel, thanks for posting!  I'm not seeing this.  It should show you the active agents based on the `From` and `To` fields that are set below the agent selection.  Maybe it's confusing because the `From` and `To` dates are below the agent selection, or because they do not carry over from the time period you were viewing before you go to the Report page?  I think I will probably change both of those things to avoid that confusion, but let me know if that's it or if you are seeing something else.  Thanks.

**Comment by webjoel** [comment]
Hi,

Perfect! This is it. Change filter order.

**Comment by trask** [comment]
Great! This is done now in the latest snapshot release [glowroot-central-0.10.5-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.5-SNAPSHOT).
