### ISSUE TITLE
Publish docker image for the central collector

### ISSUE THREAD

**Issue by trask** [glowroot/glowroot#337]

**Comment by fedecz** [comment]
Thanks Trask for opening this up. It'd be good if environment variables were used for common configuration, instead of having to rely on a configuration file being fed to the container. I've always found env variables much easier to deal with, instead of creating a volume...putting the file there, etc.

Is the application now accepting -D variables to override configs?

**Comment by trask** [comment]
Hi @fedecz!  That sounds like a good way to go.  I'll update the central collector to accept system property overrides, and use that to pass in environment variables from the container.

**Comment by trask** [comment]
I added support for system property overrides, but ended up modeling after Cassandra's Dockerfile (https://github.com/docker-library/cassandra/tree/master/3.11).

To try it out:

```
docker run --name mycassandra -d cassandra
docker run --name myglowroot --link mycassandra:cassandra -p 127.0.0.1:4000:4000 glowroot/glowroot-central:0.10.5
```
