### ISSUE TITLE
Laggy scrolling for the new query stats from slow traces

### ISSUE THREAD

**Issue by ionutursuleanu** [glowroot/glowroot#359]
Hi,

Scrolling through the new query stats is very laggy on safari 11.1 (macOS 10.13.4). Chrome & Firefox scrolling is smooth

Thanks,
Ionut

**Comment by trask** [comment]
Hi @ionutursuleanu, thanks for reporting this!  I can repro the same, that's soooo slow!  I'll look into it.

**Comment by trask** [comment]
This should be fixed now in the latest snapshot releases [glowroot-agent-0.11.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.11.0-SNAPSHOT) and [glowroot-central-0.10.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.13-SNAPSHOT)! It was fixed by upgrading to Bootstrap 4 and re-working the trace modal to be more Bootstrap-y.

**Comment by ionutursuleanu** [comment]
Thank you
