### ISSUE TITLE
glowroot and spring batch

### ISSUE THREAD

**Issue by quochoangnguyen** [glowroot/glowroot#385]
Hi  Trask,

I want to know if glowroot is the  appropriate tool to make profiling operations with java batch programs developed with  spring batch framework ?

Thank in advance

**Comment by trask** [comment]
Hi @quochoangnguyen, thanks for posting! Yes, Glowroot is designed to work with this type of application as well. You will need to tell Glowroot what it should use for transaction demarcation. I looked at the Spring Batch API, and this might be good (Configuration > Instrumentation > Import):

```
{
  "className": "org.springframework.batch.core.Step",
  "methodName": "execute",
  "methodParameterTypes": [
    "org.springframework.batch.core.StepExecution"
  ],
  "captureKind": "transaction",
  "transactionType": "Background",
  "transactionNameTemplate": "Spring Batch: {{this.name}}",
  "traceEntryMessageTemplate": "Spring Batch: {{this.name}}",
  "timerName": "spring batch"
}
```

Let me know how this goes, Spring Batch support might be nice to add to the Glowroot Spring Plugin so that it would work out of the box for everyone.

**Comment by quochoangnguyen** [comment]
Hi Trask,

It worked well

Here are some extracts of screenshot from Glowroot GUI
![glowroot_springbatch_test_image1](https://user-images.githubusercontent.com/6152245/40120909-9804ce7c-5920-11e8-97a0-92a69019389c.png)
![glowroot_springbatch_test_image2](https://user-images.githubusercontent.com/6152245/40120917-9b561a86-5920-11e8-8591-abadc2808798.png)
![glowroot_springbatch_test_image3](https://user-images.githubusercontent.com/6152245/40120921-9d6ff508-5920-11e8-8525-7c9c3a725253.png)
![glowroot_springbatch_test_image4](https://user-images.githubusercontent.com/6152245/40120926-9f153198-5920-11e8-94ad-9a7778ddbd91.png)

Thank a lot for your help

**Comment by trask** [comment]
Thanks for the screenshots. This instrumentation is now part of the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT).
