### ISSUE TITLE
Weaving blacklist required

### ISSUE THREAD

**Issue by sldab** [glowroot/glowroot#395]
We are using Apache Ignite in our clustered application with Ignite's `OptimizedMarshaller`.
The `OptimizedMarshaller` is simply based on `ObjectOutputStream` and does not enforce serialized objects to implement the `Serializable` interface.

If we activate or deactivate the Glowroot agent on one of the nodes, it crashes upon start as Ignite bootstrap messages from other nodes cannot be unmarshalled due to incompatible `ObjectOutputStream`s.

Falling back to the `JdkMarshaller` that relies on plain java serialization is an option, but only works if the classes of all cached objects are serializable or externalizable.

I am missing an option that would allow me to configure a list of packages and/or classes to be blacklisted for weaving in the UI and `config.json`. Ideally, custom instrumentations should override this blacklist, so I can pick classes of interest of a blacklisted package.

Do you see any issues with such a functionality?

**Comment by trask** [comment]
Hi @sldab, thanks for reporting this! I think the problem is that Glowroot was not marking fields it adds as `transient`. I'm hoping this is fixed now in the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT).

**Comment by sldab** [comment]
Hi @trask, thank you for fixing this so quickly. I like this fix very much. Tested it with the snapshot version and it looks fine.

My gut feeling tells me that we still might need some sort of instrumentation blacklist for debugging purposes if we roll out the agent on a bigger scale. But let's see...
