### ISSUE TITLE
Background threads

### ISSUE THREAD

**Issue by code4free** [glowroot/glowroot#396]
I am trying to use glowroot to profile my application, but I have noticed it doesn't support profiling of background threads.

I am invoking REST request to my application which essentially does:
new Thread(myJob).start();

Is it suppose to be working? If yes then how should I configure it?

**Comment by trask** [comment]
Hi @code4free, thanks for posting!

The problem is that Glowroot doesn't know if the REST request is going to wait for `myJob` to complete (in which case it captures it as part of the REST request), or whether it should capture `myJob` as a new (Background) transaction.

I added new instrumentation option "What to do if already in a transaction" in the latest snapshot release [glowroot-agent-0.10.10-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.10-SNAPSHOT), so you can now create a new Instrumentation (via the Glowroot UI) to force `myJob` to start a new transaction even though it is already inside the REST transaction.

The "Class name" for the instrumentation would be the class of `myJob`.  The "Method name" would be "run".  "What to capture" would be "Transaction".

Let me know if this makes sense / works out.

**Comment by code4free** [comment]
Hello @trask, 
Thanks for the changes. I have managed to set it up and it worked the first time! Really cool.

One minor thing to consider (although I don't need it right now), would be to extend the template language for transaction names to allow to refer to the name of the parent transaction e.g. "{{parent.transaction.name}}". It would work out nicely with the possibility of explicit name assignment via "Glowroot-Transaction-Name" HTTP header.

Anyway thank you very much! You have solved my issue. So far the workaround that I have used was to disable the servlet plugin. Unfortunately the only way I have found out to do it was by modifying the glowroot.plugins.json file inside glowroot.jar.

**Comment by shark-horse** [comment]
I asked on another issue, but maybe it's more appropriate here: How does Glowroot decide what threads are auxiliary threads and what threads are unrelated? We have an app where all threads are unrelated, from the point-of-view of JDBC transactions, but Glowroot is complaining about auxiliary threads leaking resources and not finishing, when even the concept of relating any other threads to the transaction seems entirely invalid to me.
