### ISSUE TITLE
Docker and agent.id

### ISSUE THREAD

**Issue by mmornati** [glowroot/glowroot#399]
We are using Glowroot witt the Central Collector for 2 applications having multiple instances anyone. All is managed using Docker (1 instance of the application = 1 container).

The problem is that the name used, even with the rollup configuration, is containing the container ID. So, anytime we are deploying a new version of the application, the container ID is changing and I will have a new "entry" into the glowroot agent combo box.

<img width="221" alt="capture d ecran 2018-05-31 a 20 15 07" src="https://user-images.githubusercontent.com/139323/40799969-5bc2da80-650f-11e8-9cfd-bbaaf78062e7.png">

As I can't stuck the name of the agent due to the multiple instances (I don't know how many instances of the Application A I will have 'cause it depends on the load) is there a different way to keep this name fixed (API-01, API-02, API-03, ...).
I there any way to remove the old entries using the web interface?

**Comment by trask** [comment]
Hi @mmornati, thanks for posting! The agent dropdown was previously showing agents that were active in the time range being viewed, but it only used 24-hour precision to detect agent activity, so the dropdown could end up showing agents that weren't really active during the time range being viewed (especially if your agents start/stop often). I have updated this now in the latest snapshot release [glowroot-central-0.10.12-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.12-SNAPSHOT) to use 5-min precision instead of 24-hour precision. I'm hoping this better precision will make the dropdown more useful and address your needs. This new 5-min precision is only captured going forward after upgrading to the latest version, so there will still be 24-hour rounding errors when viewing a time range prior to upgrade.
