### ISSUE TITLE
Alternative Collector is not working because of shading the api in the agent

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#42]
When building a alternative Collector, implementing the [Collector](https://github.com/glowroot/glowroot/blob/master/wire-api/src/main/java/org/glowroot/wire/api/Collector.java) API. It is not picked up because the agent is looking for `org.glowroot.agent.shaded.glowroot.wire.api.Collector`

Two solutions:
- disable shading of this API package, but when disabling the shading the project won't build;
- add shading to your own project, that's working, you would need it anyway.

**Comment by trask** [comment]
Ah yes, the reason the wire-api is shaded now inside the agent is so that the agent can be used to monitor glowroot central itself (which also uses wire-api).  Since glowroot central doesn't need to be shaded (thankfully), it seems better to keep all of the (sometimes painful) shading work at the agent level.  As you mention, you'll need to shade protobuf at least anyways in a custom collector, so I think it makes sense to go ahead and shade wire-api there also.

**Comment by ajdevries** [comment]
Clear... Shaded jar is working. Thanks for the quick reply.
