### ISSUE TITLE
Allow initial port and host configuration from jvm arguments

### ISSUE THREAD

**Issue by bmarwell** [glowroot/glowroot#423]
Hi,

this site: https://github.com/glowroot/glowroot/wiki/Agent-Installation-(with-Embedded-Collector)

says: once ran once, edit the admin.json file.

For a big environment, this is not feasible. Also, for a deployment, creating a small admin.json file would be an unnessecary step.

Please allow options like:
* `-Dglowroot.agent.port=4000`
* `-Dglowroot.agent.host=localhost`

Thanks!

**Comment by bmhm** [comment]
Hi @trask ,

not everyone uses docker. Image deploying multiple jvms on a single machine, but using the same .jar file. Bevor starting ANY jvm, I'd need to manually create the `conf/agentid/admin.json` file. Just using a jvm option is so much easier for deployments, because you have to create the `jvm.options` file anyway.

Also, if a deployment needed to create the file manually, it would need to know the infrastructure -- e.g. by reading the glowroot.properties file. But that task should belong to the `glowroot.jar` library, not to any user's deployment script.

This is why I think a jvm option would be feasible.

**Comment by trask** [comment]
Thanks, I forgot about multiple jvms on one machine, you're right, this is a problem.

**Comment by trask** [comment]
Hi @bmhm, would the user/role setup be the same for all JVMs? I think new agents should pick up default `config.json` and `admin.json` from the shared conf directory in the multiple JVM case (this would help https://groups.google.com/d/msg/glowroot/oUfwfdoTPIc/CL6LKDbxBgAJ also).

**Comment by bmhm** [comment]
Hi @trask,

yes, the user/role setup would be the same. I just tried to create the `admin-default.json`, but it did not get picked up in the current version. 

The default config just wouldn't help with the ports, obviously. 

Thanks a lot, great tool! Easiest to configure and the default (embedded) DB is sufficient for so many use cases! :)

**Comment by trask** [comment]
Hi @bmhm, the latest snapshot release [glowroot-agent-0.10.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.13-SNAPSHOT) now supports `admin-default.json` and `-Dglowroot.agent.port=`. Let me know if this works out for you. Thanks.

**Comment by bmhm** [comment]
@trask thanks, both options do work fine. Settings from `admin-default.json` were read (guest == non-admin, context-root = `/glowroot`), as well as the agent port. Haven't tried bindAddress through `admin-default.json`, though. Thanks!

**Comment by bmhm** [comment]
Hi,
I found out that the `admin-default.json` is not in conf.dir, but in `glowroot.dir`. Directories are the same IF `glowroot.properties` does not exist.

But the behaviour is as expected.

We should just make sure that the `admin-default.json` is documented correctly.

**Comment by trask** [comment]
Hi @bmhm, thanks for pointing this out, I've updated the code to look in both places now (first `conf.dir` then `glowroot.dir`).
