### ISSUE TITLE
Support heap histogram on IBM J9

### ISSUE THREAD

**Issue by trask** [glowroot/glowroot#430]
Currently, the heap histogram screen displays "This feature is not available when the agent is running in IBM J9 VM."

**Comment by bmhm** [comment]
Great! Anyway, I'd consider this not too important. Nice feature to have, but in the end it's just a graph which is missing.

**Comment by trask** [comment]
Yeah, I rarely find heap histogram useful anyways (I removed it completely at one point, but later decided it was occasionally useful). Closing for now, tagged with wishlist label (lower priority enhancements that have been closed to keep the open backlog manageable).

**Comment by bmhm** [comment]
Agreed. If I do have the time, I'll look into it.

**Comment by bmhm** [comment]
As information: Heap analysis is available using IBM Memory Analyzer Tool (MAT).

https://www.ibm.com/developerworks/community/blogs/kevgrig/entry/how_to_use_the_memory_analyzer_tool_mat_to_compare_heapdumps_and_system_dumps20?lang=en

Noteworthy: glowroot will not compile in openj9 (or any other j9), because obfuscation will fail.

I also dug around a little. It seems the class which needs to be attached to is `ibm.tools.attach.J9VirtualMachine` instead of `sun.tools.attach.HotSpotVirtualMachine` in `JvmTool.java`.

But for OpenJ9 it was changed to: `com.ibm.tools.attach.attacher.OpenJ9VirtualMachine extends com.sun.tools.attach.VirtualMachine`.

Hope that helps!

**Comment by bmhm** [comment]
Wrap an if around these lines:

**Comment by trask** [comment]
Hi @bmhm, I tried what you suggested, but `com.ibm.tools.attach.attacher.OpenJ9VirtualMachine` has no method similar to `heapHisto()`, which is the method Glowroot calls to get the heap histogram on other JVMs.

The [IBM link](https://www.ibm.com/developerworks/community/blogs/kevgrig/entry/how_to_use_the_memory_analyzer_tool_mat_to_compare_heapdumps_and_system_dumps20?lang=en) above requires taking a full heap dump first, and then loading/parsing it to generate the heap histogram, which is much more expensive compared to the more lightweight `heapHisto()` method provided on other JVMs.

**Comment by bmhm** [comment]
Thanks a lot for your research effort!

@trask if you are interested in getting this method implemented in IBM j9 and openJ9, feel free to vote. All you need is an IBM id (which can be created for free, it's just a user account).

http://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=125480
