### ISSUE TITLE
Ability to manually start/stop transaction

### ISSUE THREAD

**Issue by bourretp** [glowroot/glowroot#439]
Hi,

I try to instrument [Apache Camel](http://camel.apache.org/) routers so I can
* start a transaction when a message enters the route
* stop the transaction when a message exits the route.

The problem is that routes are build using a DSL (http://camel.apache.org/java-dsl.html) and there is no specific class/method for the route being built, and I see no way to instrument that route using AOP.

Is there a way to completely bypass the AOP approach and to manually
* start a new transaction at some point 
* stop at a later point (same thread! :)

Pseudo-code:

```java
    from("file:src/data?noop=true")
        .process(() -> {/* Start transaction here ? */})
        // Content of the route here...
        // ...
        .process(() -> {/* Stop transaction here ? */})
    .to("file:target/messages/uk")
```

**Comment by trask** [comment]
Hi @bourretp, thanks for posting! My concern about having separate start/stop is that you have to be really sure that stop gets called, otherwise abandoned trace could cause memory leak. Instead, if they are being called by the same thread, I try to instrument the caller of both of the methods. I took a look at Apache Camel, and created a (starter) plugin that I think(?) accomplishes what you are looking for. This is available now in the latest snapshot release [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT).
