### ISSUE TITLE
Support for different application servers

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#44]
Is there a list for supported application servers? Right now I'm testing with Glassfish 4.1.1 and it seems that glowroot isn't working. Investigating things now. Seeing this in the server.log:
```
[2015-12-15T17:37:14.191+0100] [glassfish 4.1] [SEVERE] [NCLS-CORE-00029] [javax.enterprise.system.core] [tid: _ThreadID=81 _Thre
Cannot start container web, exception: A MultiException has 2 exceptions.  They are:
1. java.lang.NoClassDefFoundError: org/glowroot/agent/plugin/servlet/ServletAspect$HttpServletRequest
2. java.lang.IllegalStateException: Unable to perform operation: post construct on com.sun.enterprise.web.WebContainer
]]
```

**Comment by trask** [comment]
Thanks for reporting this.  I looked into it and the main issue was the Glassfish OSGi class loader not looking at the bootstrap class loader for Glowroot classes.  I ran into a similar issue previously with JBoss/Wildfly (which has its own OSGi-ish modularization).

I just pushed a couple of commits and it seems to be working with Glassfish now.  Please try the latest snapshot build (https://s3.amazonaws.com/glowroot/snapshots/glowroot-0.9-SNAPSHOT-dist.zip).

Glowroot should support Tomcat, TomEE, Jetty, JBoss, Wildfly and (now) Glassfish.  Once upon a time (~4 years ago) it supported WebLogic and WebSphere, but it's been a long time since I've personally used either of those, so YMMV, but it would be great if you report any issues you run into with any application servers (listed above or not).

**Comment by ajdevries** [comment]
Tested, and issue is fixed. Any hints on how to fix this by myself, adjust logging, etc.?

**Comment by trask** [comment]
Great.  In this case, I attached Eclipse debugger to Glassfish and put a breakpoint inside the NoClassDefFoundError constructor, and then walked the stack at the breakpoint to see what class loader was being used, and why it wasn't finding the glowroot classes (which are in the JVM bootstrap class loader).
