### ISSUE TITLE
Latency in aggregation of rollup data

### ISSUE THREAD

**Issue by pavanimanthana** [glowroot/glowroot#449]
This issue is raised for the google group discussion https://groups.google.com/forum/#!topic/glowroot/hzJWL5FnKig

For high volume of agent data the aggregation process slows down and the data has a lag in UI for up to a few hours.

**Comment by trask** [comment]
More improvements done in 663072ab58d7354650aec02aaec9b28f5369e52c

**Comment by ReillyProcentive** [comment]
I'm not seeing a real improvement in performance since updating our central server from `0.10.12+the previous patch` to `0.12.3`. CPU usage is about the same as it was before the update. We might not be noticing the improvement though given that we are no longer bottlenecked.

**Comment by trask** [comment]
I think this is addressed pretty well in the latest snapshot release [glowroot-central-0.13.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.0-SNAPSHOT).

In addition to optimizations to make single threaded rollup faster, the central collector also now will add/remove rollup threads automatically in order to try to keep overall rollup time somewhere between 1 and 5 minutes.
