### ISSUE TITLE
Hi i have completed below steps, but i cant start the application

### ISSUE THREAD

**Issue by vijaynet10** [glowroot/glowroot#496]
1.Download and unzip glowroot-0.12.3-dist.zip
2.Add -javaagent:path/to/glowroot.jar to your application's JVM args [where are my application server's JVM args?]
3.Check that the user account that runs the JVM has write access to the glowroot folder
4.Start your application

but i cant start the application.please help me to configure

_Originally posted by @vijaynet10 in https://github.com/glowroot/glowroot/issue_comments#issuecomment-448575446_

**Comment by Niks1820** [comment]
Hi Vijay,
You are not able to start the application, is it related to your own application or glowroot. If you can share the server logs it would be more clear.

**Comment by vijaynet10** [comment]
i am not able to run the glow root. and the server log is 
"2018-12-19 16:06:59.848 INFO  org.glowroot - To run Glowroot, you need to add "-javaagent:/opt/apache-tomcat/glowroot/glowroot.jar" to your application's JVM args"

**Comment by vijaynet10** [comment]
any update @Niks1820

**Comment by Niks1820** [comment]
Download the glowroot jar and place it on your server on the above path. Now if it is a web based ear or microservice jar you will need to pass the javaagent argument in the script file by which you start the server.

**Comment by trask** [comment]
Hi @vijaynet10, 

I think the message you got:

`2018-12-19 16:06:59.848 INFO org.glowroot - To run Glowroot, you need to add "-javaagent:/opt/apache-tomcat/glowroot/glowroot.jar" to your application's JVM args`

means that you tried to run using `java -jar path/to/glowroot.jar ...`, instead of `java -javaagent:path/to/glowroot.jar -jar ...`

If you are still having issues, can you post the exact command you are running?

**Comment by trask** [comment]
Closing, but please re-open if you are still facing this issue. Thanks.
