### ISSUE TITLE
How to use org.glowroot.agent.api.Glowroot to modify a spring controller transaction name?

### ISSUE THREAD

**Issue by Owenong** [glowroot/glowroot#499]
Hi,

In my application, I would like to modify the transaction name to have a prefix (for my multi-tenancy application). I am using Glowroot.setTransactionName in my controller but it seems no effect. May I know what is the correct way to use this API or how can I add a prefix to all the transactions name? Thanks.

**Comment by Owenong** [comment]
Realized that I have to use "provided" scope to include dependency.

**Comment by trask** [comment]
Hi @Owenong, thanks for reporting this! I'm re-opening it, because it *should* work the way you originally expected it to (and shouldn't work the way it actually *does* work).

I want it to work when the agent-api is bundled with your application, so that your application will work whether or not the glowroot agent is actually running (the agent-api should default to no-op when the agent is not actually running).

**Comment by trask** [comment]
Hi @Owenong, this should be fixed now in the latest snapshot release [glowroot-agent-0.13.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.0-SNAPSHOT).

**Comment by Owenong** [comment]
Hi @trask, thanks for the fixes and new build.
