### ISSUE TITLE
glowroot slows down Liferay DXP (tomcat9) startup 

### ISSUE THREAD

**Issue by davidepolli** [glowroot/glowroot#520]
Hi,

recently I've been trying to use glowroot for monitoring a Liferay DXP cluster and it looks like the overhead on application startup is far from "difficult to measure".

Liferay runs on Tomcat9 (tomcat-9.0.6) app server and, without glowroot we have startup time of about 80 seconds, with glowroot agent, the mean startup time raise to about 100 seconds.

Can you suggest how to reduce this impact? Is there any way to understand in which way glowroot is having such a great impact?

Regards,
Davide

**Comment by trask** [comment]
Hi @davidepolli, thanks for posting!  Startup time is a definitely impacted, since that is when classes are loaded and the initial bytecode instrumentation takes place.

That said, I tried out Liferay (which loads a lot of classes!) and took another crack at tuning the initial bytecode instrumentation, and was able to cut the startup overhead approximately in half.

You'll won't notice this improvement until the second startup, because the optimization works by capturing some data on the first startup (stored in a new file under `glowroot/tmp/preload-some-super-types-cache`) and then using that data to optimize future startups.

This optimization is available now in the latest snapshot release [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT).

**Comment by davidepolli** [comment]
hi @trask,
thanks for your answer and for taking care of analize and develop a fix, i'll soon try the new version and share the results.

Regards,
Davide
