### ISSUE TITLE
Tombstones limit problem

### ISSUE THREAD

**Issue by lukaszun** [glowroot/glowroot#521]
Hi,
from some time we're experiencing problem with cassandra and glowroot.

While browsing transaction we got following error:

An error occurred
com.datastax.driver.core.exceptions.ReadFailureException: Cassandra failure during read query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)

In Cassandra:

Scanned over 100001 tombstones during query 'SELECT * FROM glowroot.trace_tt_slow_point_partial WHERE agent_rollup, transaction_type = .....

How can we fix it?

**Comment by trask** [comment]
Hi @lukaszun, thanks for reporting this!

I just optimized these trace "partial" tables so that central collector should write about 20x fewer tombstones to those tables now.

This optimization is available (as long as you are using Cassandra 3.0+) in the latest snapshot release [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT).

It won't reduce tombstones written prior to the fix, but those should get compacted away after a while by Cassandra.

Let me know how it goes.
