### ISSUE TITLE
Leaked connection detection

### ISSUE THREAD

**Issue by lfen21** [glowroot/glowroot#523]
Hi

Do you think there is a way to do database connection leaks detection via glowroot ? 

Thanks

**Comment by bmhm** [comment]
Hi @lfen21,
this is already possible. Most connection pools do expose open connections via MBean or MXBean.
Add a gauge for them and you are done.

If you want to have this as default, add a default config next to the glowroot.jar file.

**Comment by lfen21** [comment]
hm not exactly what i wanted but interesting

**Comment by trask** [comment]
Hi @lfen21, I added leaked connection detection to the latest snapshot release [glowroot-agent-0.13.4-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.4-SNAPSHOT). So far, it covers Apache Commons DBCP, HikariCP, Tomcat Connection Pool, Glassfish Connection Pool, and Bitronix Connection Pool.

If it detects a leaked connection, it will mark the transaction as an error, and note the object that leaked. In order to get stack trace of the location where the connection was borrowed (and never returned), you need to enable "Connection pool leak details" under Configuration > Plugins > Jdbc Plugin.

**Comment by ThiagoMenezesAbreu** [comment]
This is awesome.
But, is not possible to use J2EE interfaces like getConnection/close to support everything?

**Comment by lfen21** [comment]
Hi
Wildfly is using ajurna, is  it possible to detect leaked connection for it ? 
Thanks

**Comment by shark-horse** [comment]
@trask Would you please explain (e.g. with a link) how the leak detection works, or point me to the code change introducing it?
