### ISSUE TITLE
Possible memory leak - Webflux with Tailable and event-stream

### ISSUE THREAD

**Issue by justme02** [glowroot/glowroot#546]
Hi,
I have an application that is build with spring webflux and it streams events from MongoDb to end user. I observed that gloowroot share in occupy memory is high (much higher than in other our applications).  As I mention in subject I use mongodb cursor to fetch new data and stream it to user. Each user open its own stream. Let me know if you need more information to solve this issue. 
 version:
Central collector version 0.13.0, built 2019-01-14 00:54:38 +0000
Agent version 0.13.0, built 2019-01-14 00:54:38 +0000
![possible_memory_leak](https://user-images.githubusercontent.com/48319560/53955684-f1c7e100-40d9-11e9-96e8-78f8190e0b3a.png)

**Comment by trask** [comment]
Hi @justme02, thanks for reporting this! Any chance you could capture a heap dump and upload to me at https://www.dropbox.com/request/Yo15bgWhhQS1K7qyA6wK?

**Comment by justme02** [comment]
Heap dump has been uploaded.

**Comment by trask** [comment]
Hi @justme02, I found an issue where Glowroot was not ending (and releasing) async transactions when the client disconnected (as opposed to server explicitly ending the request). I suspect this is what was happening in your case since you are sending back a (never ending) stream from the server. I think this should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).

**Comment by justme02** [comment]
Hi, 
@trask thank you for fixing it and your hard work :)
