### ISSUE TITLE
Support for BEA jolt/Tuxedo ?

### ISSUE THREAD

**Issue by abhinav-nath** [glowroot/glowroot#555]
Hi,

My Java API applications runs on Weblogic server and connects to BEA Jolt in order to communicate with back-end Tuxedo services (written in C).

After installing Glowroot in my Java application, I can see almost all stats except traces for Jolt calls.

Can someone please help me out here ? I really wish to see the details about Jolt service calls in the traces. Is there a way I could add a custom trace plugin for Jolt ?

Thanks in advance !

**Comment by trask** [comment]
Hi @abhinav-nath, thanks for posting!

I'm not familiar with Jolt, but it looks like you would want to put instrumentation on https://docs.oracle.com/cd/E13161_01/tuxedo/docs10gr3/javadoc/jolt/javadoc/bea/jolt/pool/SessionPool.html#call(java.lang.String,%20bea.jolt.pool.DataSet,%20bea.jolt.pool.Transaction) in order to capture those calls.

The easiest way to add this instrumentation would be in the Glowroot UI, under Configuration > Instrumentation, let me know if you have any trouble with this.
