### ISSUE TITLE
Configuration external Collector

### ISSUE THREAD

**Issue by ajdevries** [glowroot/glowroot#62]
When using an external Collector via the Collector API. It would be nice to get the endpoint settings (and other settings) from the glowroot configuration.

Currently I'm searching for a config.yml to get the right endpoint, but this is hard because I don't know on with path the application (and agent) is started. So I'm using glowroot.base.dir at the moment.

It would be nice to use the glowroot.properties or an alternative config file (yaml?)

**Comment by trask** [comment]
It's not pretty, but I think this should get you the base directory where you can store/read yaml/properties file:
`new File(MyCollector.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath())
.getParentFile().getParentFile()`

Btw, when I tested this with a custom collector, I noticed that there was an annoying condition that required you to have a dummy glowroot.properties file (or some other equally unpleasant workaround) in order to trigger the thin agent init. This is fixed in ee7fbbe130ab99068eeb835f137622063553d0f3.

**Comment by ajdevries** [comment]
Thanks! I will give it a try. And true, I needed to set to host in the properties file ;-)

**Comment by ajdevries** [comment]
This works, thanks!

**Comment by ajdevries** [comment]
This isn't working when running in one-jar mode. Maybe the baseDir can be passed in the init method?

**Comment by trask** [comment]
Is this what you're using? http://one-jar.sourceforge.net

**Comment by ajdevries** [comment]
No, I rebuild the previous distribution with fancy glow root-maven-packager ;-) Great stuff, need to adapt to some changes and will make a PR for it. You could even put the packager back in

**Comment by trask** [comment]
Passing base dir to `Collector.init()` now in c12a553b5f673d2d65b5e01238945f9df73c1200 as you suggested. Thanks.

**Comment by ajdevries** [comment]
Thanks... Made a PR for the packager plugin https://github.com/glowroot/glowroot/pull/65. And experimented with a smaller zip. Excluding netty and h2 gives me a 5Mb smaller package. But I'm running into some ThinAgent dependencies, like [CollectorLogbackAppender#40](https://github.com/glowroot/glowroot/blob/master/agent-parent/agent/src/main/java/org/glowroot/agent/init/CollectorLogbackAppender.java#L40)

**Comment by ajdevries** [comment]
Continuing in other issue #60
